
server:
  port: 8080
  servlet:
    contextPath: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zepsight?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    database: mysql
    #    database-platform: com.hospital.petcare.common.config.dialect.MySqlCustomDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      use_sql_comments: true
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true

  jackson:
    serialization:
      indent_output: true

